name: Deploy GitHub Pages

on:
  push:
    branches: [stable]
    paths:
      - 'docs/**'
      - 'modules/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v31.4.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4.2.2
      - name: Nix build
        working-directory: ./docs
        run: nix build
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./docs/result

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
